### ISSUE TITLE
Add phantom type parameter (like ST) to prevent IVar escape

### ISSUE THREAD

**Issue by rrnewton** [simonmar/monad-par#3]
As described in the paper, currently IVars can be returned from Par computations and then used in other Par computations.  This can be prevented in the type system but it hasn't been done yet.

**Comment by ezyang** [comment]
Well, in any case, the Haddock docs really should mention that IVars should not escape...

**Comment by rrnewton** [comment]
Yes, true.

**Comment by rrnewton** [comment]
Done, version bumped and uploaded.

Closing this issue because we're unlikely to actually change the API for the monad-par package.  We do plan to finally release a 2.0 version of LVish soon, however.
