### ISSUE TITLE
Duplicate documentation in Haddocks

### ISSUE THREAD

**Issue by MaxGabriel** [simonmar/monad-par#40]
The current Haddocks have duplicate lines for several of the functions. Potentially this is caused by documenting both the original function and the export? I'm not sure yet. 

Would you like me to look into cleaning this up?

<hr>

Example:

```haskell
put_ :: IVar a -> a -> Par ()
```

> like put, but only head-strict rather than fully-strict.

> like put, but only head-strict rather than fully-strict.

![image](https://cloud.githubusercontent.com/assets/1274145/7986928/63615c7c-0a8f-11e5-8205-3fe2a2df7c6b.png)

https://hackage.haskell.org/package/monad-par-0.3.4.7/docs/Control-Monad-Par.html

**Comment by rrnewton** [comment]
Ouch, that's ugly.  Yes, let's fix it.
