### ISSUE TITLE
Second listing in "Other Slides" 404s

### ISSUE THREAD

**Issue by MaxGabriel** [simonmar/monad-par#41]
The second link under "Other Slides" on [this page of the documentation](https://hackage.haskell.org/package/monad-par-0.3.4.7/docs/Control-Monad-Par.html) 404s.

http://www.cs.indiana.edu/~rrnewton/talks/2011_HaskellSymposium_ParMonad.pdf

Should it just be removed?

**Comment by rrnewton** [comment]
Thanks for catching that!  The link works again now.

**Comment by WendaoLee** [comment]
This link is 404 again.👀Is there any other sources or ways to fix it?
