### ISSUE TITLE
Test suite fails on powerpc

### ISSUE THREAD

**Issue by nomeata** [simonmar/monad-par#44]
Hi,

when trying to build this on powerpc with GHC-7.10, I observe sporadic test failures. Unfortunately, Cabal is not very chatty, so I cannot say much:
```
Running debian/hlibrary.setup test --builddir=dist-ghc --show-details=always
Running 1 test suites...
Test suite test-monad-par: RUNNING...
Test suite test-monad-par: FAIL
Test suite logged to: dist-ghc/test/monad-par-0.3.4.7-test-monad-par.log
0 of 1 test suites (0 of 1 test cases) passed.
```
https://buildd.debian.org/status/fetch.php?pkg=haskell-monad-par&arch=powerpc&ver=0.3.4.7-6%2Bb1&stamp=1446555170

The fact that there is no output at all might indicate a GHC bug, so I’m pinging @erikd because often architecture-specific bugs are only ever fixed if he is involved...

**Comment by erikd** [comment]
There are at least two important fixes that have been added in 7.10.3 that are not in 7.10.2.

I have a patched ghc-7.10.2 with which these test pass without a problem.

**Comment by nomeata** [comment]
This is GHC-7.10.3-rc1.

But if the tests pass for you, then maybe it is the Cabal bug that breaks test suites with more output than fits into a buffer? But I thought that would only occur when there is no threaded runtime that can be used for setup, and here setup is compiled with `-threaded` :-(

**Comment by erikd** [comment]
Oh, yes, I see its `ghc-7.10.2.20151030`.

Initially I ran the test as `dist/build/test-monad-par/test-monad-par` because I wanted to see the errors but there were none. I just ran it now as `cabal test` and that too passes with flying colours.

Is it possible to get the file `dist-ghc/test/monad-par-0.3.4.7-test-monad-par.log` ?

**Comment by nomeata** [comment]
> Is it possible to get the file dist-ghc/test/monad-par-0.3.4.7-test-monad-par.log ?

Not easily, but according to the code path in Cabal, it will not contain anything that is not printed to stdout; in particular, the output of the test suite is empty.

**Comment by erikd** [comment]
Dang! I consider this a bug in cabal!

**Comment by nomeata** [comment]
Yes, that’d be https://github.com/haskell/cabal/issues/2398.

Although I thought it would only happen without `-threaded`.

**Comment by erikd** [comment]
No, I meant that cabal redirecting/hiding test output is a bug :-).

**Comment by nomeata** [comment]
Then also see https://github.com/haskell/cabal/issues/2911 :-)

**Comment by erikd** [comment]
Well done!

**Comment by nomeata** [comment]
I cooked up a patch to implement haskell/cabal#2911, which works around haskell/cabal#2398, and I’m going to upload a patched ghc package containing this patch to Debian soon.

**Comment by nomeata** [comment]
Ok, the Cabal patch resolved this issue. Sorry, Simon, for the noise on your bug tracker:
https://buildd.debian.org/status/fetch.php?pkg=haskell-monad-par&arch=powerpc&ver=0.3.4.7-6%2Bb1&stamp=1446764468
