### ISSUE TITLE
Is it possible to add a MonadFix instance?

### ISSUE THREAD

**Issue by treeowl** [simonmar/monad-par#46]
The original paper gives an example of a parallel type checker that manually creates `IVars` rather than using `spawn` or `spawn_`. It advertises that this avoids needing to deal with a fixed-point function. Well, tastes vary in all things, and I personally think it would be very nice to have that fixed-point function! Is it feasible to implement a `MonadFix` instance, or is the CPSish representation (or something else) incompatible with that?

**Comment by simonmar** [comment]
I have no idea.  Feel free to try it and see!
