### ISSUE TITLE
monad-par-0.3.4.9 violated PVP by introducing new features

### ISSUE THREAD

**Issue by phadej** [simonmar/monad-par#68]
> Non-breaking change. Otherwise, if only new bindings, types, classes, non-orphan instances or modules (but see below) were added to the interface, then A.B MAY remain the same but the new C MUST be greater than the old C. Note that modifying imports or depending on a newer version of another package may cause extra non-orphan instances to be exported and thus force a minor version change.

Between 0.3.4.8 and 0.3.4.9 I see added `fixPar` combinators, and `MonadFix` instances.

cc @hvr

I'd recommend blacklisting the release, and re-releasing it as `0.3.5`.

**Comment by hvr** [comment]
Besides the serious undersignalling of API changes, the version bounds need some love too as can be seen at https://matrix.hackage.haskell.org/package/monad-par@1572855411

**Comment by simonmar** [comment]
Uploaded 0.3.5
