### ISSUE TITLE
[Docs Typo]Some links of reference in the comments were outdated 

### ISSUE THREAD

**Issue by WendaoLee** [simonmar/monad-par#78]
For instance,in `Control.Monad.Par`,the annotations

```
The original paper (http://www.cs.indiana.edu/~rrnewton/papers/haskell2011_monad-par.pdf)
```

are outdated.Only got `404 NOT FOUND` when try to view the source.I think it would be helpful to fix this typo in order to make it convenient for others.

I notice that Mr.Marlow‘s blog on Github has that source file. e.g [http://simonmar.github.io/bib/papers/monad-par.pdf](http://simonmar.github.io/bib/papers/monad-par.pdf)

Would it better to replace that with the outdated in the comments,or just add citation of that paper?

**Comment by WendaoLee** [comment]
Btw,if you don't have time to fix that,I would like to offer pr to fix that.

**Comment by ocharles** [comment]
A PR would be very welcome!

**Comment by WendaoLee** [comment]
The links which were outdated are:
- `The original paper`
For that I have found that paper in Mr.Marlow's blog:[http://simonmar.github.io/bib/papers/monad-par.pdf](http://simonmar.github.io/bib/papers/monad-par.pdf)
- `Tutorial slides`
For this I have found the copy at h[ttps://www.cse.unt.edu/~tarau/teaching/parpro/papers/CUFP.pdf](https://www.cse.unt.edu/~tarau/teaching/parpro/papers/CUFP.pdf)
- The second link of `Other slides`
Util now I haven't found the slides' source file.But I noticed the issue #41 .It seems that this link can be fix?But across 8 years I'm not sure.
If remove this source,I think it seems not polite to the author.

**Comment by WendaoLee** [comment]
#79
